kind: pipeline
type: docker
name: build

steps:
- name: build
  image: node
  volumes:
  - name: build
    path: /build
  commands:
  - (cd home && npm install)
  - (cd home && npx tailwindcss -i ./src/input.css -o /build/output.css --minify)
  - cp -f ./home/src/index.html /build/index.html
  - cp -f ./home/src/*.svg /build/

- name: publish
  image: amazon/aws-cli
  volumes:
  - name: build
    path: /build
  - name: aws
    path: /root/.aws
  commands:
  - aws s3 sync /build s3://duffle.one --acl public-read --follow-symlinks --delete

volumes:
  - name: build
    temp: {}
  - name: aws
    host:
      path: /root/.aws
