kind: pipeline
type: docker
name: build and publish

steps:
- name: build
  image: node
  commands:
  - (cd home && npm install)
  - (cd home && npm run build)
  - cp -f ./home/src/index.html ./build/index.html
  - cp -f ./home/src/*.svg ./build/
