---
kind: pipeline
type: docker
name: build and publish

steps:
- name: build_home
  image: node
  volumes:
  - name: build
    path: /build
  commands:
  - (cd home && npm install)
  - (cd home && npx @tailwindcss/cli -i ./src/input.css -o /build/output.css --minify)
  - cp -f ./home/src/index.html /build/index.html
  - cp -f ./home/src/*.svg /build/

- name: build_display
  image: alpine
  volumes:
  - name: build
    path: /build
  commands:
  - mkdir -p /build/display
  - cp -f ./display/index.html /build/display/index.html
  - cp -f ./display/*.svg /build/display/

- name: publish development
  image: amazon/aws-cli
  volumes:
  - name: build
    path: /build
  - name: aws
    path: /root/.aws
  commands:
  - aws s3 sync /build s3://duffle.one/dev --acl public-read --follow-symlinks
  depends_on:
  - build_home
  - build_display
  when:
    ref:
      exclude:
      - refs/heads/master
    event:
    - push

- name: publish production
  image: amazon/aws-cli
  volumes:
  - name: build
    path: /build
  - name: aws
    path: /root/.aws
  commands:
  - aws s3 sync /build s3://duffle.one --acl public-read --follow-symlinks --delete
  depends_on:
  - build_home
  - build_display
  when:
    ref:
    - refs/heads/master
    event:
    - push

volumes:
  - name: build
    temp:
      medium: memory
  - name: aws
    host:
      path: /root/.aws
---
kind: signature
hmac: f5f02609c0a993c1c90dcd92ec635d11a9f427316f75f7b6b1c6abb871d742a2

...
