---
kind: pipeline
type: docker
name: build and publish

steps:
- name: build_home
  image: node
  volumes:
  - name: build
    path: /build
  commands:
  - (cd home && npm install)
  - (cd home && npx tailwindcss -i ./src/input.css -o /build/output.css --minify)
  - cp -f ./home/src/index.html /build/index.html
  - cp -f ./home/src/*.svg /build/

- name: build_display
  image: alpine
  volumes:
  - name: build
    path: /build
  commands:
  - mkdir -p /build/display
  - cp -f ./display/index.html /build/display/index.html
  - cp -f ./display/*.svg /build/display/

- name: publish
  image: amazon/aws-cli
  volumes:
  - name: build
    path: /build
  - name: aws
    path: /root/.aws
  commands:
  - aws s3 sync /build s3://duffle.one --acl public-read --follow-symlinks --delete
  depends_on:
  - build_home
  - build_display
  when:
    ref:
    - refs/heads/master
    event:
    - push

volumes:
  - name: build
    temp: {}
  - name: aws
    host:
      path: /root/.aws
---
kind: signature
hmac: 16b37251d9f66a194d2e7d351a6067037ec7ddb3557d4d826a288efde7584f5d

...
