---
kind: pipeline
type: docker
name: build and publish

steps:
  - name: build_site
    image: node:20
    environment:
      BUILD_DIR: /build
      CI: true
    volumes:
      - name: build
        path: /build
    commands:
      - npm ci
      - npm run build

  - name: publish production
    image: amazon/aws-cli
    volumes:
      - name: build
        path: /build
      - name: aws
        path: /root/.aws
    commands:
      - aws s3 sync /build s3://duffle.one --acl public-read --follow-symlinks --delete
      - aws s3 cp /build/index.html s3://duffle.one/index.html --acl public-read --content-type text/html --cache-control "no-cache, no-store, must-revalidate" --metadata-directive REPLACE
      - aws s3 cp /build/404.html s3://duffle.one/404.html --acl public-read --content-type text/html --cache-control "no-cache, no-store, must-revalidate" --metadata-directive REPLACE
      - aws s3 website s3://duffle.one/ --index-document index.html --error-document 404.html
    depends_on:
      - build_site
    when:
      branch:
        - master
      event:
        - push

volumes:
  - name: build
    temp: {}
  - name: aws
    host:
      path: /root/.aws
---
kind: signature
hmac: 2a4142c1ac91623ada905a99d83bfcaca9dfc760f78b81119e34966514ebbec2

...
