<?php

$emoji = [
	"confirmed" => "bi-check-circle",
	"pending" => "bi-hourglass-split",
];

$events = [
	[
		"name" => "KV - E1",
		"link" => "https://klubverboten.com/dates",
		"image" => "assets/images/events/kv.png",
		"kink" => true,
		"date" => "Mar 17",
		"location" => "London 🇬🇧",
		"status" => "confirmed",
	],
	[
		"name" => "Pedestal",
		"link" => "https://www.clubpedestal.com/main.html",
		"image" => "assets/images/events/pedestal.gif",
		"kink" => true,
		"date" => "Mar 30",
		"location" => "London 🇬🇧",
		"status" => "confirmed",
	],
	[
		"name" => "Le Boutique Bazaar",
		"link" => "https://dice.fm/partner/le-boutique-bazaar/event/96ypd-le-boutique-bazaar-wild-spring-2nd-apr-fyeo-london-tickets",
		"image" => "assets/images/events/lbb.avif",
		"kink" => true,
		"date" => "Apr 2",
		"location" => "London 🇬🇧",
		"status" => "confirmed",
	],
	[
		"name" => "LAM",
		"link" => "https://londonalternativemarket.com/",
		"image" => "assets/images/events/lam.webp",
		"kink" => true,
		"date" => "Apr 2",
		"location" => "London 🇬🇧",
		"status" => "confirmed",
		"items" => [
			[
				"text" => "After party only",
				"emoji" => "bi-slash-square",
			],
		],
	],
	[
		"name" => "KV - TEARS FOR BEERS",
		"link" => "https://klubverboten.com/dates",
		"image" => "assets/images/events/kv.png",
		"kink" => true,
		"date" => "Apr 5",
		"location" => "London 🇬🇧",
		"status" => "confirmed",
	],
	[
		"name" => "Club AntiChrist - 19th Birthday",
		"link" => "https://www.clubantichrist.co.uk/events/19thbirthday",
		"image" => "assets/images/events/ac.png",
		"kink" => true,
		"date" => "May 12",
		"location" => "London 🇬🇧",
		"status" => "confirmed",
	],
	[
		"name" => "Naughties London",
		"link" => "https://fetlife.com/events/1267189",
		"image" => "assets/images/events/blank.png",
		"kink" => true,
		"date" => "May 19",
		"location" => "London 🇬🇧",
		"status" => "confirmed",
	],
	[
		"name" => "MCM Comic Con",
		"link" => "https://www.mcmcomiccon.com/london/en-us/home.html",
		"image" => "assets/images/events/comiccon.png",
		"kink" => false,
		"date" => "May 26 - 28",
		"location" => "London 🇬🇧",
		"status" => "confirmed",
	],
	[
		"name" => "Club Labrys",
		"link" => "https://www.bizarre-events.com/club-labrys",
		"image" => "assets/images/events/clublabrys.webp",
		"kink" => true,
		"date" => "June 2",
		"location" => "London 🇬🇧",
		"status" => "pending",
	],
	[
		"name" => "The Big One - Club o&I/LAM",
		"link" => "https://fetlife.com/events/1241601",
		"image" => "assets/images/events/lam.webp",
		"kink" => true,
		"date" => "Aug 13",
		"location" => "Kent 🇬🇧",
		"status" => "pending",
	],
];
