<?php

$emoji = [
    'confirmed' => 'bi-check-circle',
    'maybe' => 'bi-arrow-left-right',
    'pending' => 'bi-hourglass-split',
    'unlikely' => 'bi-hand-thumbs-down',
];

$events = [
    [
        'name' => 'DEBAUCHERY',
        'link' => 'https://fetlife.com/events/1283967',
        'image' => 'assets/images/events/dby.jpeg',
        'kink' => true,
        'date' => 'Jun 24',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'Play munch',
        'link' => 'https://fetlife.com/events/1305783',
        'image' => 'assets/images/events/blank.png',
        'kink' => true,
        'date' => 'Jun 27',
        'location' => 'London 🇬🇧',
        'status' => 'pending',
    ],
    [
        'name' => 'LAM',
        'link' => 'https://londonalternativemarket.com/',
        'image' => 'assets/images/events/lam.webp',
        'kink' => true,
        'date' => 'Jul 2',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'KV - TEARS FOR BEERS',
        'link' => 'https://klubverboten.com/dates',
        'image' => 'assets/images/events/kv.png',
        'kink' => true,
        'date' => 'Jul 5',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'Naughties',
        'link' => 'https://fetlife.com/events/1283417',
        'image' => 'assets/images/events/blank.png',
        'kink' => true,
        'date' => 'Jul 8',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'DEBAUCHERY',
        'link' => 'https://fetlife.com/events/1283968',
        'image' => 'assets/images/events/dby.jpeg',
        'kink' => true,
        'date' => 'Jul 22',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'Club Pedestal',
        'link' => 'https://www.clubpedestal.com/main.html',
        'image' => 'assets/images/events/pedestal.gif',
        'kink' => true,
        'date' => 'Jul 27',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'Club Labrys',
        'link' => 'https://www.bizarre-events.com/club-labrys',
        'image' => 'assets/images/events/clublabrys.webp',
        'kink' => true,
        'date' => 'Aug 11',
        'location' => 'London 🇬🇧',
        'status' => 'pending',
    ],
    [
        'name' => 'The Big One - Club o&I/LAM',
        'link' => 'https://fetlife.com/events/1241601',
        'image' => 'assets/images/events/lam.webp',
        'kink' => true,
        'date' => 'Aug 13',
        'location' => 'Kent 🇬🇧',
        'status' => 'pending',
    ],
];

// Not used, just for Copy pasting recurring events
$recurring = [
    [
        'name' => 'Charm Skool Pop Up',
        'link' => 'https://www.eventbrite.co.uk/e/charmskool-erotic-pop-up-shop-social-tickets-638781080407',
        'image' => 'assets/images/events/charmskool.jpeg',
        'kink' => true,
        'date' => 'XXX',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'Naughties',
        'link' => 'https://fetlife.com/events/1291166',
        'image' => 'assets/images/events/blank.png',
        'kink' => true,
        'date' => 'XXX',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'Club AntiChrist - 19th Birthday',
        'link' => 'https://www.clubantichrist.co.uk/events/19thbirthday',
        'image' => 'assets/images/events/ac.png',
        'kink' => true,
        'date' => 'XXX',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'One Night',
        'link' => 'https://www.onenightparties.com/',
        'image' => 'assets/images/events/onenight.jpg',
        'kink' => true,
        'date' => 'XXX',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'KV - TEARS FOR BEERS',
        'link' => 'https://klubverboten.com/dates',
        'image' => 'assets/images/events/kv.png',
        'kink' => true,
        'date' => 'XXX',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'KV - E1',
        'link' => 'https://klubverboten.com/dates',
        'image' => 'assets/images/events/kv.png',
        'kink' => true,
        'date' => 'XXX',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'Club Pedestal',
        'link' => 'https://www.clubpedestal.com/main.html',
        'image' => 'assets/images/events/pedestal.gif',
        'kink' => true,
        'date' => 'XXX',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'Le Boutique Bazaar',
        'link' => 'https://dice.fm/partner/le-boutique-bazaar/event/96ypd-le-boutique-bazaar-wild-spring-2nd-apr-fyeo-london-tickets',
        'image' => 'assets/images/events/lbb.avif',
        'kink' => true,
        'date' => 'XXX',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'LAM',
        'link' => 'https://londonalternativemarket.com/',
        'image' => 'assets/images/events/lam.webp',
        'kink' => true,
        'date' => 'XXX',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
        'items' => [
            [
                'text' => 'After party only',
                'emoji' => 'bi-slash-square',
            ],
        ],
    ],
    [
        'name' => 'DEBAUCHERY',
        'link' => 'https://fetlife.com/events/1260555',
        'image' => 'assets/images/events/dby.jpeg',
        'kink' => true,
        'date' => 'May 27',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
    [
        'name' => 'Club Labrys',
        'link' => 'https://www.bizarre-events.com/club-labrys',
        'image' => 'assets/images/events/clublabrys.webp',
        'kink' => true,
        'date' => 'XXX',
        'location' => 'London 🇬🇧',
        'status' => 'pending',
    ],
    [
        'name' => 'MCM Comic Con',
        'link' => 'https://www.mcmcomiccon.com/london/en-us/home.html',
        'image' => 'assets/images/events/comiccon.png',
        'kink' => false,
        'date' => 'May 26 - 28',
        'location' => 'London 🇬🇧',
        'status' => 'confirmed',
    ],
];
